#!/usr/bin/env node
/**
 * Copy forge ABIs + deployment addresses into @lacrew/core.
 * Run after `forge build` (and optionally after a forge script deploy).
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const coreRoot = resolve(__dirname, "..");
const repoRoot = resolve(coreRoot, "../..");
const contractsOut = join(repoRoot, "contracts/out");
const deploymentsDir = join(coreRoot, "deployments");

const CONTRACTS = [
  {
    name: "IPolicyModule",
    file: "IPolicyModule.sol/IPolicyModule.json",
    exportName: "policyModuleAbi",
  },
  { name: "OrgRegistry", file: "OrgRegistry.sol/OrgRegistry.json", exportName: "orgRegistryAbi" },
  { name: "Treasury", file: "Treasury.sol/Treasury.json", exportName: "treasuryAbi" },
  {
    name: "EscalationRouter",
    file: "EscalationRouter.sol/EscalationRouter.json",
    exportName: "escalationRouterAbi",
  },
  {
    name: "GovernanceModule",
    file: "GovernanceModule.sol/GovernanceModule.json",
    exportName: "governanceModuleAbi",
  },
  {
    name: "SpendCapPolicy",
    file: "SpendCapPolicy.sol/SpendCapPolicy.json",
    exportName: "spendCapPolicyAbi",
  },
  {
    name: "WhitelistPolicy",
    file: "WhitelistPolicy.sol/WhitelistPolicy.json",
    exportName: "whitelistPolicyAbi",
  },
  { name: "PolicyStack", file: "PolicyStack.sol/PolicyStack.json", exportName: "policyStackAbi" },
  { name: "MockUSDC", file: "MockUSDC.sol/MockUSDC.json", exportName: "mockUsdcAbi" },
  {
    name: "RateLimitPolicy",
    file: "RateLimitPolicy.sol/RateLimitPolicy.json",
    exportName: "rateLimitPolicyAbi",
  },
  {
    name: "TimeWindowPolicy",
    file: "TimeWindowPolicy.sol/TimeWindowPolicy.json",
    exportName: "timeWindowPolicyAbi",
  },
  {
    name: "EpochStreamer",
    file: "EpochStreamer.sol/EpochStreamer.json",
    exportName: "epochStreamerAbi",
  },
  {
    name: "SessionRegistry",
    file: "SessionRegistry.sol/SessionRegistry.json",
    exportName: "sessionRegistryAbi",
  },
  {
    name: "MarketplacePayments",
    file: "MarketplacePayments.sol/MarketplacePayments.json",
    exportName: "marketplacePaymentsAbi",
  },
];

function loadAbi(relPath) {
  const full = join(contractsOut, relPath);
  if (!existsSync(full)) {
    throw new Error(`Missing forge artifact: ${full}\nRun: cd contracts && forge build`);
  }
  const artifact = JSON.parse(readFileSync(full, "utf8"));
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`No abi in ${full}`);
  }
  return artifact.abi;
}

function writeAbisTs(abisByExport) {
  const parts = [
    "/**",
    " * Generated by packages/core/scripts/sync-abis.mjs — do not edit by hand.",
    " * Source: contracts/out/*.sol/*.json after `forge build`.",
    " */",
    "",
  ];
  for (const [exportName, abi] of Object.entries(abisByExport)) {
    parts.push(`export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;`, "");
  }
  writeFileSync(join(coreRoot, "src/abis.ts"), parts.join("\n"));
}

const KNOWN_CHAIN_IDS = ["31337", "11155111", "84532"];

function extractDeploymentsFromBroadcast(chainId) {
  const broadcastRoot = join(repoRoot, "contracts/broadcast/DeployMockOrg.s.sol");
  const latest = join(broadcastRoot, chainId, "run-latest.json");
  if (!existsSync(latest)) return null;
  const run = JSON.parse(readFileSync(latest, "utf8"));
  const created = run.transactions?.filter((t) => t.transactionType === "CREATE") ?? [];
  const byName = {};
  for (const tx of created) {
    if (tx.contractName && tx.contractAddress) {
      byName[tx.contractName] = tx.contractAddress;
    }
  }
  if (!byName.OrgRegistry) return null;
  return {
    chainId: Number(chainId),
    mockUSDC: byName.MockUSDC ?? "0x0000000000000000000000000000000000000000",
    orgRegistry: byName.OrgRegistry,
    treasury: byName.Treasury,
    escalationRouter: byName.EscalationRouter,
    governanceModule: byName.GovernanceModule,
    spendCapPolicy: byName.SpendCapPolicy,
    policyStack: byName.PolicyStack,
    whitelistPolicy: byName.WhitelistPolicy,
    epochStreamer: byName.EpochStreamer,
    sessionRegistry: byName.SessionRegistry,
  };
}

function writeDeploymentsJson(addresses) {
  mkdirSync(deploymentsDir, { recursive: true });
  const chainFile = join(deploymentsDir, `${addresses.chainId}.json`);
  writeFileSync(chainFile, `${JSON.stringify(addresses, null, 2)}\n`);

  if (addresses.chainId === 31337) {
    writeFileSync(join(deploymentsDir, "anvil.json"), `${JSON.stringify(addresses, null, 2)}\n`);
  }

  // Also mirror under contracts/deployments for forge script consumers.
  const contractsDeploy = join(repoRoot, "contracts/deployments");
  mkdirSync(contractsDeploy, { recursive: true });
  writeFileSync(
    join(contractsDeploy, `${addresses.chainId}.json`),
    `${JSON.stringify(addresses, null, 2)}\n`,
  );
}

/** Known Anvil demo accounts — only ever used as fallbacks on chain 31337. */
const ANVIL_NODE_DEFAULTS = {
  humanRoot: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
  manager: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
  worker: "0xCcBcac53a38c585bA0caf2270dd2d906f14dac88",
  x402Target: "0xC7240d92d1bd7114fB3eeaDC9934d11AaCebe27a",
};

/**
 * Prefer forge script JSON (includes org node accounts); fall back to
 * broadcast CREATEs. Anvil-account defaults never leak onto real chains.
 */
function loadDeploymentsForChain(chainId) {
  const file = join(repoRoot, `contracts/deployments/${chainId}.json`);
  if (existsSync(file)) {
    const data = JSON.parse(readFileSync(file, "utf8"));
    if (data.orgRegistry && data.manager) {
      return data;
    }
    // Script may have been overwritten by an older sync — merge broadcast CREATEs.
    const fromBroadcast = extractDeploymentsFromBroadcast(chainId);
    if (fromBroadcast && chainId === "31337") {
      return { ...ANVIL_NODE_DEFAULTS, ...data, ...fromBroadcast };
    }
    return fromBroadcast ? { ...data, ...fromBroadcast } : data;
  }
  const fromBroadcast = extractDeploymentsFromBroadcast(chainId);
  if (fromBroadcast && chainId === "31337") {
    return { ...ANVIL_NODE_DEFAULTS, ...fromBroadcast };
  }
  return fromBroadcast;
}

function writeDeploymentsTs() {
  mkdirSync(deploymentsDir, { recursive: true });
  const files = ["anvil.json", "31337.json", "11155111.json", "84532.json"];
  const entries = [];

  for (const file of files) {
    const path = join(deploymentsDir, file);
    if (!existsSync(path)) continue;
    const data = JSON.parse(readFileSync(path, "utf8"));
    if (typeof data.chainId !== "number") continue;
    entries.push([data.chainId, data]);
  }

  // Deduplicate by chainId (prefer higher-specificity numeric file over anvil alias).
  const byChain = new Map();
  for (const [chainId, data] of entries) {
    byChain.set(chainId, data);
  }

  const body = [
    "/** Generated by packages/core/scripts/sync-abis.mjs — do not edit by hand. */",
    "",
    'import type { ChainAddresses } from "./types.js";',
    "",
    "export const DEPLOYMENTS: Record<number, ChainAddresses> = {",
  ];

  for (const [chainId, data] of [...byChain.entries()].sort((a, b) => a[0] - b[0])) {
    body.push(`  ${chainId}: ${JSON.stringify(data, null, 2).replace(/\n/g, "\n  ")},`);
  }

  body.push("};", "");
  writeFileSync(join(coreRoot, "src/deployments.generated.ts"), body.join("\n"));
}

/**
 * A chain gets an address book when it has actually been deployed to, and not
 * before.
 *
 * This used to synthesise `0x…01`–`0x…07` entries for Base Sepolia and an anvil
 * alias. Those look like deployments: `getAddresses` returns them, the
 * orchestrator builds an "onchain" runtime from them, and every read then
 * reverts or returns zero — which the UI renders as an empty org rather than as
 * a chain nobody deployed to. That is the same failure mode as serving mock
 * data, only harder to notice, so the placeholders are gone. Callers that need
 * to know should ask `hasDeployment(chainId)`.
 *
 * `anvil.json` is still written, but only as an alias of a real 31337 deploy.
 */
function writeAnvilAlias(addresses) {
  if (addresses?.chainId !== 31337) return;
  mkdirSync(deploymentsDir, { recursive: true });
  writeFileSync(
    join(deploymentsDir, "anvil.json"),
    `${JSON.stringify(addresses, null, 2)}\n`,
  );
}

function main() {
  // No forge artifacts (Docker builds, fresh checkouts without foundry):
  // keep the committed generated files — they are the source of truth until
  // someone actually rebuilds the contracts.
  const artifactsReady = CONTRACTS.every((c) => existsSync(join(contractsOut, c.file)));
  if (!artifactsReady) {
    if (!existsSync(join(coreRoot, "src/abis.ts"))) {
      throw new Error(
        "Missing forge artifacts and no committed src/abis.ts — run: cd contracts && forge build",
      );
    }
    console.warn(
      "[sync-abis] forge artifacts missing — keeping committed abis.ts/deployments (cd contracts && forge build to regenerate)",
    );
    return;
  }

  const abis = {};
  for (const c of CONTRACTS) {
    abis[c.exportName] = loadAbi(c.file);
  }
  writeAbisTs(abis);

  for (const chainId of KNOWN_CHAIN_IDS) {
    const deployments = loadDeploymentsForChain(chainId);
    if (!deployments) continue;
    if (!deployments.orgRegistry) {
      console.warn(`Skipping chain ${chainId}: incomplete deployment JSON`);
      continue;
    }
    writeDeploymentsJson(deployments);
    writeAnvilAlias(deployments);
    console.log(`Synced deployments for chain ${deployments.chainId}`);
  }

  writeDeploymentsTs();
  console.log("Synced ABIs → packages/core/src/abis.ts");
  console.log("Synced deployments → packages/core/src/deployments.generated.ts");
}

main();
