#!/usr/bin/env node
/**
 * Copy forge ABIs + deployment addresses into @lacrew/core.
 * Run after `forge build` (and optionally after a forge script deploy).
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const coreRoot = resolve(__dirname, "..");
const repoRoot = resolve(coreRoot, "../..");
const contractsOut = join(repoRoot, "contracts/out");
const deploymentsDir = join(coreRoot, "deployments");

const CONTRACTS = [
  { name: "OrgRegistry", file: "OrgRegistry.sol/OrgRegistry.json", exportName: "orgRegistryAbi" },
  { name: "Treasury", file: "Treasury.sol/Treasury.json", exportName: "treasuryAbi" },
  {
    name: "EscalationRouter",
    file: "EscalationRouter.sol/EscalationRouter.json",
    exportName: "escalationRouterAbi",
  },
  {
    name: "GovernanceModule",
    file: "GovernanceModule.sol/GovernanceModule.json",
    exportName: "governanceModuleAbi",
  },
  {
    name: "SpendCapPolicy",
    file: "SpendCapPolicy.sol/SpendCapPolicy.json",
    exportName: "spendCapPolicyAbi",
  },
  { name: "PolicyStack", file: "PolicyStack.sol/PolicyStack.json", exportName: "policyStackAbi" },
  { name: "MockUSDC", file: "MockUSDC.sol/MockUSDC.json", exportName: "mockUsdcAbi" },
];

function loadAbi(relPath) {
  const full = join(contractsOut, relPath);
  if (!existsSync(full)) {
    throw new Error(`Missing forge artifact: ${full}\nRun: cd contracts && forge build`);
  }
  const artifact = JSON.parse(readFileSync(full, "utf8"));
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`No abi in ${full}`);
  }
  return artifact.abi;
}

function writeAbisTs(abisByExport) {
  const parts = [
    "/**",
    " * Generated by packages/core/scripts/sync-abis.mjs — do not edit by hand.",
    " * Source: contracts/out/*.sol/*.json after `forge build`.",
    " */",
    "",
  ];
  for (const [exportName, abi] of Object.entries(abisByExport)) {
    parts.push(`export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;`, "");
  }
  writeFileSync(join(coreRoot, "src/abis.ts"), parts.join("\n"));
}

function extractDeploymentsFromBroadcast() {
  const broadcastRoot = join(repoRoot, "contracts/broadcast/DeployMockOrg.s.sol");
  if (!existsSync(broadcastRoot)) return null;

  // Prefer latest run for anvil (31337).
  const chainIds = ["31337", "84532"];
  for (const chainId of chainIds) {
    const latest = join(broadcastRoot, chainId, "run-latest.json");
    if (!existsSync(latest)) continue;
    const run = JSON.parse(readFileSync(latest, "utf8"));
    const created = run.transactions?.filter((t) => t.transactionType === "CREATE") ?? [];
    const byName = {};
    for (const tx of created) {
      if (tx.contractName && tx.contractAddress) {
        byName[tx.contractName] = tx.contractAddress;
      }
    }
    if (!byName.OrgRegistry) continue;
    return {
      chainId: Number(chainId),
      mockUSDC: byName.MockUSDC ?? "0x0000000000000000000000000000000000000000",
      orgRegistry: byName.OrgRegistry,
      treasury: byName.Treasury,
      escalationRouter: byName.EscalationRouter,
      governanceModule: byName.GovernanceModule,
      spendCapPolicy: byName.SpendCapPolicy,
      policyStack: byName.PolicyStack,
      whitelistPolicy: byName.WhitelistPolicy,
    };
  }
  return null;
}

function writeDeploymentsJson(addresses) {
  mkdirSync(deploymentsDir, { recursive: true });
  const chainFile = join(deploymentsDir, `${addresses.chainId}.json`);
  writeFileSync(chainFile, `${JSON.stringify(addresses, null, 2)}\n`);

  if (addresses.chainId === 31337) {
    writeFileSync(join(deploymentsDir, "anvil.json"), `${JSON.stringify(addresses, null, 2)}\n`);
  }

  // Also mirror under contracts/deployments for forge script consumers.
  const contractsDeploy = join(repoRoot, "contracts/deployments");
  mkdirSync(contractsDeploy, { recursive: true });
  writeFileSync(
    join(contractsDeploy, `${addresses.chainId}.json`),
    `${JSON.stringify(addresses, null, 2)}\n`,
  );
}

function writeDeploymentsTs() {
  mkdirSync(deploymentsDir, { recursive: true });
  const files = ["anvil.json", "31337.json", "84532.json"];
  const entries = [];

  for (const file of files) {
    const path = join(deploymentsDir, file);
    if (!existsSync(path)) continue;
    const data = JSON.parse(readFileSync(path, "utf8"));
    if (typeof data.chainId !== "number") continue;
    entries.push([data.chainId, data]);
  }

  // Deduplicate by chainId (prefer higher-specificity numeric file over anvil alias).
  const byChain = new Map();
  for (const [chainId, data] of entries) {
    byChain.set(chainId, data);
  }

  const body = [
    "/** Generated by packages/core/scripts/sync-abis.mjs — do not edit by hand. */",
    "",
    'import type { ChainAddresses } from "./types.js";',
    "",
    "export const DEPLOYMENTS: Record<number, ChainAddresses> = {",
  ];

  for (const [chainId, data] of [...byChain.entries()].sort((a, b) => a[0] - b[0])) {
    body.push(`  ${chainId}: ${JSON.stringify(data, null, 2).replace(/\n/g, "\n  ")},`);
  }

  body.push("};", "");
  writeFileSync(join(coreRoot, "src/deployments.generated.ts"), body.join("\n"));
}

function ensurePlaceholderDeployments() {
  mkdirSync(deploymentsDir, { recursive: true });
  const placeholder = {
    chainId: 31337,
    mockUSDC: "0x0000000000000000000000000000000000000000",
    orgRegistry: "0x0000000000000000000000000000000000000001",
    treasury: "0x0000000000000000000000000000000000000002",
    escalationRouter: "0x0000000000000000000000000000000000000003",
    governanceModule: "0x0000000000000000000000000000000000000004",
    spendCapPolicy: "0x0000000000000000000000000000000000000005",
    policyStack: "0x0000000000000000000000000000000000000006",
    whitelistPolicy: "0x0000000000000000000000000000000000000007",
  };
  const anvilPath = join(deploymentsDir, "anvil.json");
  if (!existsSync(anvilPath)) {
    writeFileSync(anvilPath, `${JSON.stringify(placeholder, null, 2)}\n`);
  }
  const sepoliaPath = join(deploymentsDir, "84532.json");
  if (!existsSync(sepoliaPath)) {
    writeFileSync(
      sepoliaPath,
      `${JSON.stringify({ ...placeholder, chainId: 84532 }, null, 2)}\n`,
    );
  }
}

function main() {
  const abis = {};
  for (const c of CONTRACTS) {
    abis[c.exportName] = loadAbi(c.file);
  }
  writeAbisTs(abis);

  ensurePlaceholderDeployments();
  const fromBroadcast = extractDeploymentsFromBroadcast();
  if (fromBroadcast) {
    writeDeploymentsJson(fromBroadcast);
    console.log(`Wrote deployments for chain ${fromBroadcast.chainId} from forge broadcast`);
  }

  // Prefer contracts/deployments written by forge script if present.
  const contractsAnvil = join(repoRoot, "contracts/deployments/31337.json");
  if (existsSync(contractsAnvil)) {
    const data = JSON.parse(readFileSync(contractsAnvil, "utf8"));
    writeDeploymentsJson(data);
    console.log("Synced contracts/deployments/31337.json → packages/core/deployments");
  }

  writeDeploymentsTs();
  console.log("Synced ABIs → packages/core/src/abis.ts");
  console.log("Synced deployments → packages/core/src/deployments.generated.ts");
}

main();
