/** Generated by packages/core/scripts/sync-abis.mjs — do not edit by hand. */

import type { ChainAddresses } from "./types.js";

export const DEPLOYMENTS: Record<number, ChainAddresses> = {
  31337: {
    "chainId": 31337,
    "mockUSDC": "0x36C02dA8a0983159322a80FFE9F24b1acfF8B570",
    "orgRegistry": "0x809d550fca64d94Bd9F66E60752A544199cfAC3D",
    "treasury": "0xc351628EB244ec633d5f21fBD6621e1a683B1181",
    "escalationRouter": "0x7bc06c482DEAd17c0e297aFbC32f6e63d3846650",
    "governanceModule": "0x4c5859f0F772848b2D91F1D83E2Fe57935348029",
    "spendCapPolicy": "0xb7278A61aa25c888815aFC32Ad3cC52fF24fE575",
    "policyStack": "0x7969c5eD335650692Bc04293B07F5BF2e7A673C0",
    "whitelistPolicy": "0x1291Be112d480055DaFd8a610b7d1e203891C274",
    "humanRoot": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "manager": "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
    "worker": "0xCcBcac53a38c585bA0caf2270dd2d906f14dac88",
    "x402Target": "0xC7240d92d1bd7114fB3eeaDC9934d11AaCebe27a"
  },
  84532: {
    "chainId": 84532,
    "mockUSDC": "0x0000000000000000000000000000000000000000",
    "orgRegistry": "0x0000000000000000000000000000000000000001",
    "treasury": "0x0000000000000000000000000000000000000002",
    "escalationRouter": "0x0000000000000000000000000000000000000003",
    "governanceModule": "0x0000000000000000000000000000000000000004",
    "spendCapPolicy": "0x0000000000000000000000000000000000000005",
    "policyStack": "0x0000000000000000000000000000000000000006",
    "whitelistPolicy": "0x0000000000000000000000000000000000000007"
  },
};
